use_frameworks!

platform :ios, '9.0'

target 'MCSHelloWorld_Example' do
  pod 'MCSHelloWorld', :path => '../'

  target 'MCSHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
